version: "1"
services:
  app:
    build: .
    container_name: app
    command: uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/
    ports:
      - 8000:8000
